### ISSUE TITLE
Update map markers based on weather

### ISSUE THREAD

**Issue by lavishabhambri** [MLH-Fellowship/prep-project-22.OCT.PREP.1#13]
## Description
Update the markers in the map for showing the weather at a particular location entered by user.

**Comment by lavishabhambri** [comment]
@akshitadixit, I and @niyoj want to work on this issue too. Can you assign it to us?

**Comment by akshitadixit** [comment]
Once we have a PR for the previous one, sure :)

**Comment by gauravgulati15** [comment]
@lavishabhambri The point 1, you mentioned is issue #5, and @amv2 and I raised the PR for that. We also put the markers but for now, it doesn't show any information. You can work on the markers once our PR is resolved.

**Comment by lavishabhambri** [comment]
Sorry, I missed issue 5, I will update this issue. Thanks @gauravgulati15 for bringing this to attention.

**Comment by gauravgulati15** [comment]
@lavishabhambri are you working on this issue? if not, can @amv2 and I work on this?

**Comment by lavishabhambri** [comment]
Yes, @niyoj was working on this issue.

**Comment by lavishabhambri** [comment]
@akshitadixit Can you assign the issue to me & @niyoj . We are done with the PR of the previous assigned issue.

**Comment by lavishabhambri** [comment]
@gauravgulati15 Me & @niyoj  got stuck and facing some errors with this issue. Since, you wanted to work on this issue earlier, can you help & collaborate with us to solve the bug?

**Comment by gauravgulati15** [comment]
@lavishabhambri, I talked with @niyoj yesterday about the issue and told him to try a particular way. Did it work? and let me know if you any help.

**Comment by niyoj** [comment]
Hey @akshitadixit, we have raised PR #36 for this issue.
